name: BigBullScalpBot
description: Professional Trading Signals for Indian Stock Market
theme: jekyll-theme-cayman

# Social Media Links
telegram_bot: https://t.me/bigbullscalpbot
support_email: your_email@example.com